version: '3.8'

services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: mybarbershop-db:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mybarbershopdb
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d mybarbershopdb" ]
      interval: 5s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: mybarbershop-backend:latest
    ports:
      - "4002:4002"
    environment:
      - MYBARBERSHOP_AUTH_SECRET=devvvvvvvvvvvvv
      - MYBARBERSHOP_DB1_DRIVER=postgres
      - MYBARBERSHOP_DB1_HOST=db
      - MYBARBERSHOP_DB1_PORT=5432
      - MYBARBERSHOP_DB1_USER=user
      - MYBARBERSHOP_DB1_PASSWORD=password
      - MYBARBERSHOP_DB1_DBNAME=mybarbershopdb
      - MYBARBERSHOP_DB1_READONLY=false
      - MYBARBERSHOP_DB1_SSLMODE=disable
      - MYBARBERSHOP_DB2_DRIVER=postgres
      - MYBARBERSHOP_DB2_HOST=db
      - MYBARBERSHOP_DB2_PORT=5432
      - MYBARBERSHOP_DB2_USER=user
      - MYBARBERSHOP_DB2_PASSWORD=password
      - MYBARBERSHOP_DB2_DBNAME=mybarbershopdb
      - MYBARBERSHOP_DB2_READONLY=true
      - MYBARBERSHOP_DB2_SSLMODE=disable
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
