basePath: /api
definitions:
  admin.Input:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  admin.Output:
    properties:
      id:
        type: integer
      username:
        type: string
    type: object
  admin.PagOutput:
    properties:
      count:
        type: integer
      data:
        items:
          $ref: '#/definitions/admin.Output'
        type: array
      next:
        type: boolean
    type: object
  admin.UpdateInput:
    properties:
      password:
        type: string
    required:
    - password
    type: object
  auth.LoginInput:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  auth.LoginOutput:
    properties:
      token:
        type: string
    type: object
  barber.CheckinInput:
    properties:
      barberID:
        type: integer
      date_time:
        type: string
    required:
    - date_time
    type: object
  barber.CheckinOutput:
    properties:
      barber_id:
        type: integer
      date_time:
        type: string
      id:
        type: integer
    type: object
  barber.Input:
    properties:
      commission_rate:
        type: number
      name:
        type: string
      photo_url:
        type: string
    required:
    - name
    - photo_url
    type: object
  barber.Output:
    properties:
      commission_rate:
        type: number
      id:
        type: integer
      name:
        type: string
      photo_url:
        type: string
    type: object
  barber.PagCheckinOutput:
    properties:
      count:
        type: integer
      data:
        items:
          $ref: '#/definitions/barber.CheckinOutput'
        type: array
      next:
        type: boolean
    type: object
  barber.PagOutput:
    properties:
      count:
        type: integer
      data:
        items:
          $ref: '#/definitions/barber.Output'
        type: array
      next:
        type: boolean
    type: object
host: localhost:4002
info:
  contact: {}
  description: API for a My BarberShop application
  title: My BarberShop API
  version: "1.0"
paths:
  /admin:
    get:
      consumes:
      - application/json
      description: List all admins
      parameters:
      - description: full or partial username
        in: query
        name: username
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/admin.PagOutput'
      summary: List admins
      tags:
      - admin
    post:
      consumes:
      - application/json
      description: Add a new admin
      parameters:
      - description: Admin input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/admin.Input'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/admin.Output'
      summary: Add admin
      tags:
      - admin
  /admin/{id}:
    delete:
      consumes:
      - application/json
      description: Delete admin by ID
      parameters:
      - description: Admin ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete admin
      tags:
      - admin
    get:
      consumes:
      - application/json
      description: Get admin by ID
      parameters:
      - description: Admin ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/admin.Output'
      summary: Get admin
      tags:
      - admin
    put:
      consumes:
      - application/json
      description: Update admin by ID
      parameters:
      - description: Admin ID
        in: path
        name: id
        required: true
        type: integer
      - description: Admin update input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/admin.UpdateInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/admin.Output'
      summary: Update admin
      tags:
      - admin
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login as an admin
      parameters:
      - description: login input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.LoginOutput'
      summary: Login
      tags:
      - auth
  /barber:
    get:
      consumes:
      - application/json
      description: List all barbers
      parameters:
      - description: full or partial barber name
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/barber.PagOutput'
      summary: List barbers
      tags:
      - barber
    post:
      consumes:
      - application/json
      description: Add a new barber
      parameters:
      - description: Barber input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/barber.Input'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/barber.Output'
      summary: Add barber
      tags:
      - barber
  /barber/{id}:
    delete:
      consumes:
      - application/json
      description: Delete barber by ID
      parameters:
      - description: Barber ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete barber
      tags:
      - barber
    get:
      consumes:
      - application/json
      description: Get barber by ID
      parameters:
      - description: Barber ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/barber.Output'
      summary: Get barber
      tags:
      - barber
    put:
      consumes:
      - application/json
      description: Update barber by ID
      parameters:
      - description: Barber ID
        in: path
        name: id
        required: true
        type: integer
      - description: Barber update input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/barber.Input'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/barber.Output'
      summary: Update barber
      tags:
      - barber
  /barber/{id}/checkin:
    get:
      consumes:
      - application/json
      description: Get check-ins for a barber
      parameters:
      - description: Barber ID
        in: path
        name: id
        required: true
        type: integer
      - description: Initial date
        in: query
        name: initial_date
        type: string
      - description: Final date
        in: query
        name: final_date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/barber.PagCheckinOutput'
      summary: Get check-ins
      tags:
      - barber
    post:
      consumes:
      - application/json
      description: Add a check-in for a barber
      parameters:
      - description: Barber ID
        in: path
        name: id
        required: true
        type: integer
      - description: Check-in input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/barber.CheckinInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/barber.CheckinOutput'
      summary: Add check-in
      tags:
      - barber
swagger: "2.0"
